MercadoShark/MercadoShark/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^managerApp/', include('managerApp.urls')),
    url(r'^', include('managerApp.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MercadoShark/managerApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

app_name = 'managerApp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create_item/$', views.create_item, name='create_item'),
    url(r'^closed_item/(?P<item_id>[0-9]+)/$', views.closed_item, name='closed_item'),
    url(r'^paused_item/(?P<item_id>[0-9]+)/$', views.paused_item, name='paused_item'),
    url(r'^active_item/(?P<item_id>[0-9]+)/$', views.active_item, name='active_item'),
    url(r'^delete_item/(?P<item_id>[0-9]+)/$', views.delete_item, name='delete_item'),
    url(r'^authorize_meli$', views.authorize_meli, name='authorize_meli'),
    url(r'^authorize_meli/(?P<code>w{0,150})$', views.authorize_meli, name='authorizing_meli'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
]

MercadoShark/managerApp/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    userId = models.CharField(max_length=100)
    test_account = models.BooleanField(default=False)
    access_token = models.CharField(max_length=200, default='No acces token')
    def __str__(self):
        return 'userID: ' + str(self.user)+ ', user:' + str(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Item(models.Model):
    user = models.ForeignKey(User, default=1)
    seller = models.CharField(max_length=60, default='No especificado')
    title = models.CharField(max_length=60)
    category_id = models.CharField(max_length=60)
    price = models.FloatField(default='10')
    currency_id = models.CharField(max_length=60)
    available_quantity = models.IntegerField(default='1')
    buying_mode = models.CharField(max_length=60)
    listing_type_id = models.CharField(max_length=60)
    condition = models.CharField(max_length=60)
    description = models.CharField(max_length=9999)
    video_id = models.CharField(max_length=60)
    warranty = models.CharField(max_length=60)
    pictures = models.URLField(max_length=2000)
    itemId = models.CharField(max_length=60)
    permalink = models.URLField(max_length=2000)
    status = models.URLField(max_length=50,default='active')


    def __str__(self):
        return self.title + '. Cantidad: ' + str(self.available_quantity) + '. Precio: $' + str(self.price) + ', id ' + str(self.id)

MercadoShark/managerApp/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Item


class ItemForm(forms.ModelForm):
    styles = {'class':'form-control',
                     'style':
                         'width:80%;'
                         'margin:auto;'}

    title = forms.CharField(
        widget=forms.TextInput(
            attrs = styles
        ),
        initial='oculos Ray Ban Aviador  Que Troca As Lentes  Lancamento!'
    )

    category_id = forms.CharField(
        widget=forms.Select(
            attrs=styles,
            choices=([
       ('MLA11066', 'Accesorios para Vehiculos'),
       ('MLA11066', 'Animales y Mascotas'),
       ('MLA11066', 'Antiguedades'),
    ])))

    price = forms.FloatField(
        widget=forms.TextInput(
            attrs=styles
        ),
        initial=289
    )
    currency_id = forms.CharField(
        widget=forms.TextInput(
            attrs=styles
        ),
        initial='ARS'
    )

    available_quantity = forms.IntegerField(
        widget=forms.TextInput(
            attrs=styles
        ),
        initial=64
    )

    buying_mode = forms.CharField(
        widget=forms.Select(
            attrs=styles,
            choices=([
       ('buy_it_now', 'Comprar ahora'),
       ('buy_it_now', 'Otro (no disponible)'),
    ])))


    listing_type_id = forms.CharField(
        widget=forms.Select(
            attrs=styles,
            choices=([
       ('gold_special', 'Oro especial'),
       ('gold_special', 'Otro (no disponible)'),
    ])))

    condition = forms.CharField(
        widget=forms.Select(
            attrs=styles,
            choices=([
       ('new', 'Nuevo'),
       ('used', 'Usado'),
    ])))


    description = forms.CharField(
        widget=forms.Textarea(
            attrs=styles
        ),
        initial='Lindo Ray_Ban_Original_Wayfarer')

    warranty = forms.CharField(
        widget=forms.TextInput(
            attrs=styles
        ),
        initial='60 dias'
    )

    pictures = forms.URLField(
        widget=forms.URLInput(
            attrs=styles
        ),
        initial='http://assets.ray-ban.com//is/image/RayBan/805289653653_shad_fr?$440$'
    )

    status = forms.CharField(
        widget=forms.Select(
            attrs=styles,
            choices=([
                ('active', 'Activo'),
                ('paused', 'Pausada'),
            ])))

    class Meta:
        model = Item
        fields = [
            'title',
            'category_id',
            'price',
            'currency_id',
            'available_quantity',
            'buying_mode',
            'listing_type_id',
            'condition',
            'description',
            'warranty',
            'pictures'
        ]


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

MercadoShark/managerApp/views.py
from django.shortcuts import render, redirect
from .forms import ItemForm
from .models import Item
from api_connection import Meli_manager
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.models import User

# Init meli manager
meli_manager = Meli_manager()


def index(request):
    if request.user.is_anonymous():
        return render(request, 'managerApp/welcomeFirstTime.html')
    else:
        userData = meli_manager.get_information_user(request.user.profile.access_token)
        if userData:
            currentUser = request.user
            try:
                username = userData['nickname']
            except KeyError:
                return meli_manager.login()
            meli_manager.get_active_items_from_ML(username, currentUser)
            meli_manager.refresh_info_items(currentUser)
            items = Item.objects.filter(user=currentUser)
            delays = [.2*n for n in range(len(items))]
            return render(request, 'managerApp/index.html', {
                            'items': zip(items, delays),
                            'delays': delays})
        else:
            return render(request, 'managerApp/welcome.html')


def create_item(request):

    # if the form is vaild, publish item
    form = ItemForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        response = meli_manager.publish_item(form,request.user)

        # In case of Successful response answer
        try:
            permlink = response['permalink']
            meli_manager.create_itemObject(response,'this_username',request.user)
            return render(request, 'managerApp/modal.html', {
                'content':'El articulo se ah publicado con exito!',
                'permlink':permlink})

        # in cases of error
        except (ObjectDoesNotExist, KeyError):
            return response_errors(request, response, 'el articulo no se ah podido publicar.')

        # if the form is not valid will be returned
        # (the first time that the function is called there are no post request)
    context = { "form" : form }
    return render(request, 'managerApp/create_item.html', context)


def closed_item(request,item_id):
    return modify_listening(request, item_id, 'closed')


def paused_item(request,item_id):
    return modify_listening(request, item_id, 'paused')


def active_item(request,item_id):
    return modify_listening(request, item_id, 'active')


def delete_item(request,item_id):
    return modify_listening(request, item_id, 'delete')


def modify_listening(request, item_id, action):
    # get the item if is id is valid
    try:
        item = Item.objects.get(pk=item_id)
    except (RuntimeError, TypeError, NameError, ObjectDoesNotExist) as error:
        return manage_error(request,'El articulo dejo de existir')

    # change the listening item from Mercado Libre
    response = meli_manager.changing_listing_status(item,action,request.user)

        # in case that the answer is error
    if 'error' in response:
        return response_errors(request,response,'La operacion '  + str(action) +', no se ah podido completar. Se obtuvo: ')

    # if is not error will be deleted
    else:
        return index(request)


def authorize_meli(request):
    access_token = meli_manager.authorize_user(request)
    if request.user.is_anonymous():
        return register(request)
    request.user.profile.access_token = access_token
    request.user.save()
    return index(request)


def login_user(request):
    if request.user.is_anonymous():
        return meli_manager.login()
    else:
        username = request.user.username
        return render(request, 'managerApp/welcome.html', {'user': username})


def logout_user(request):
    logout(request)
    return redirect('https://www.mercadolibre.com/jms/mla/lgz/logout/')


def register(request):
    userData = meli_manager.get_information_user(meli_manager.access_token)
    user = authenticate(username=userData['nickname'])
    if user:
        login(request, user)
        return index(request)
    user = User()
    user.username = userData['nickname']
    user.save()
    user.profile.userId = userData['id']
    user.profile.access_token= meli_manager.access_token
    user.save()
    user = authenticate(username=userData['nickname'])
    login(request, user)
    username = user.username
    return render(request, 'managerApp/welcome.html', {'user': username})


def response_errors(request, response, type_error):
    if response['error'] == 'access_token' or response['message'] == 'Malformed access_token: null':
        return login()
    else:
        return render(request, 'managerApp/modal.html', {
            'content': 'Lamentablemente, ' + type_error + ' Se obtuvo: ' + str(
                response['message'])})


def manage_error(request, error):
    return render(request, 'managerApp/modal.html', {
        'content': 'Lamentablemente, hubo un error. Se obtuvo: ' + str(
            error)})

MercadoShark/managerApp/templates/managerApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MercadoShark{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.png' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'managerApp/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'managerApp/animate.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'managerApp/js/main.js' %}"></script>
    <script src="{% static 'managerApp/js/wow.min.js' %}"></script>
    <script>new WOW().init();</script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'managerApp:index' %}">MercadoShark</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'managerApp:login_user' %}">
                        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>&nbsp; Refrescar el Access token
                    </a>
                </li>
                <li>
                    <a href="{% url 'managerApp:create_item' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Agregar Articulo
                    </a>
                </li>
                {% block cuentasML %}
                {% endblock %}
                <li>
                    <a href="{% url 'managerApp:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Salir
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

MercadoShark/managerApp/templates/managerApp/create_item.html
{% extends 'managerApp/base.html' %}
{% block title %}Publicar un articulo{% endblock %}
{% block articles_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-offset-1 col-sm-10">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Publicar un articulo</h3>
                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'managerApp/form_template.html' %}
                        <div class="form-group">
                            <div  class="col-sm-offset-5 col-sm-11 centered">
                                <button type="submit" class="btn btn-success">    Publicar   </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

MercadoShark/managerApp/templates/managerApp/form_template.html
{% for field in form %}
    <div class="form-group row ">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="col-2 col-form-label col-sm-offset-1" for="{{field.label}}">{{ field.label_tag }}</label>
        <div class="col-4 row">
        {% if field.label_tag == description %}
            <div class="col-10">{{ field.as_textarea }}</div>
        {% elif field.label_tag == 'pictures' %}
            <div class="col-10">{{ field.button }}</div>
        {% else %}
            <div class="col-10 row">{{ field }}</div>
        {% endif %}
        </div>
    </div>
{% endfor %}

MercadoShark/managerApp/templates/managerApp/index.html
{% extends 'managerApp/base.html' %}
{% block items_active %}active{% endblock %}
{% block cuentasML %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
            Filtrar por cuenta de Mercado Libre<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            {% for account in accounts %}
            <li>
                <form action="{% url 'managerApp:select_account'  account.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                    <input type="hidden" name="account_id" value="{{  account.id }}" />
                    <button type="submit" class="btn btn-default btn-sm">
                            {{account.username}}
                    </button>
                </form>
                <form action="{% url 'managerApp:delete_account' account.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                    <input type="hidden" name="account_id" value="{{ account.id }}" />
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
            </li>
            <li class="divider"></li>
            {% endfor %}
            <li>
                <a href="{% url 'managerApp:create_testUser' %}">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Agregar Cuenta de Prueba
                </a>
            </li>
            <li>
                <a href="{% url 'managerApp:login_mlUser' %}">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Agregar Cuenta de Mercadolibre
                </a>
            </li>
        </ul>
    </li>
{% endblock %}
{% block body %}
<div class="items-container container-fluid">

    <!-- Items -->
    <div class="row">
        {% if items %}
            {% for item,delay in items %}
                <div class="col-sm-6 col-lg-4 wow zoomIn" data-wow-duration=".5s" data-wow-delay="{{delay}}s">
                    <div class="thumbnail">
                        <img src="{{ item.pictures }}" class="img-responsive">
                        <div class="caption">
                            <h3>{{ item.title }}</h3>
                            <h4>Precio: ${{ item.price }}</h4>
                            <h4 style="color:#00F">Vendedor: {{ item.account.username }}</h4>
                            <a href="{{item.permalink}}" class="btn btn-primary btn-sm" role="button">Ver publicacion</a>

                            <!-- Delete Item -->
                            <form action="{% url 'managerApp:delete_items' item.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="item_id" value="{{ item.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'managerApp:create_item' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Publicar un articulo
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

MercadoShark/managerApp/templates/managerApp/login.html
{% extends 'managerApp/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'managerApp:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'managerApp:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

MercadoShark/managerApp/templates/managerApp/login_mlUser.html
{% extends 'managerApp/base.html' %}
{% block account_active %}{{account_active}}{% endblock %}
{% block items_active %}active{% endblock %}
{% block body %}
    {% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'managerApp/style_login.css' %}"/>

<div class="container">
    <div id="login" class="signin-card">
        <div class="logo-image">
            {% load staticfiles %}
            <img src="{%  static 'favicon.png' %}" alt="Logo" title="Logo" width="138" \>
        </div>
        <h3 style="text-align:center;" class="display1">Que es   <strong style='padding:0; height:33px;  font-family: "Satisfy", cursive;' >MercadoShark</strong>?</h3>
        <div class="subhead">
            <p style="text-align:justify;"><strong> MercadoShark </strong> es una aplicacion que te permite manejar mejor tus publicaciones de MercadoLibre.
             <br><br> Inicia sesion con tu cuenta <strong> Mercado Libre </strong> para comenzar</p>
        </div>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form action="{% url 'managerApp:login_mlUser'%}" method="post" class="" role="form">
            {% csrf_token %}
            <div id="form-login-username" class="form-group">
                <input id="id_username" class="form-control" name="username" type="text" size="18" alt="login" required />
                <span class="form-highlight"></span>
                <span class="form-bar"></span>
                <label for="id_username" class="float-label">Nombre de usuario</label>
            </div>
            <div id="form-login-password" class="form-group">
                <input id="id_password" class="form-control" name="password" type="password" size="18" alt="password" required>
                <span class="form-highlight"></span>
                <span class="form-bar"></span>
                <label for="id_password" class="float-label">Contraseña</label>
            </div>
            <div>
                <button class="btn btn-block btn-info ripple-effect" type="submit" name="Submit" alt="sign in">Agregar cuenta</button>
            </div>
        </form>
    </div>
</div>


{% endblock %}

MercadoShark/managerApp/templates/managerApp/modal.html
{% extends 'managerApp/base.html' %}
{% block body %}

<div class="modal-dialog modal-lg wow zoomIn" data-wow-duration="1s">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h2 class="modal-title" id="myModalLabel">Atencion!</h2>
			<h4>{{content}}</h4>
			<script> setTimeout(function() { jQuery('#modal').modal('hide'); }, 1000); $('body').on('hidden.bs.modal', '.modal', function () { $(this).removeData('bs.modal'); }); </script>
		</div>
         <div class="modal-footer">
             <a class="btn btn-primary" data-toggle="modal" href="{% url 'managerApp:index' %}">Aceptar</a>

            {% if permlink %}
             <a class="btn btn-success" data-toggle="modal" href="{{permlink}}">Ver publicacion</a>
            {% endif %}

         </div>
	</div>
	<!-- /.modal-content -->
</div>


{% endblock %}

MercadoShark/managerApp/templates/managerApp/register.html
{% extends 'managerApp/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'managerApp/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'managerApp:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

MercadoShark/managerApp/templates/managerApp/welcome.html
{% extends 'managerApp/base.html' %}
{% block body %}
    {% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'managerApp/style_login.css' %}"/>

<div class="container">
    <div id="login" class="signin-card">
        <div class="logo-image">
            {% load staticfiles %}
            <img src="{%  static 'favicon.png' %}" alt="Logo" title="Logo" width="138" \>
        </div>
        <h3 style="text-align:center;" class="display1">Que es   <strong style='padding:0; height:33px;  font-family: "Satisfy", cursive;' >MercadoShark</strong>?</h3>
        <div class="subhead">
            <p style="text-align:justify;">Hola de nuevo!
             <br><br> Te has logeado en Mercado Libre con el usuario: <br>
                 <strong>{{user}}</strong> </p>
        </div>
        <a style="text-decoration: none;" href="{% url 'managerApp:logout_user' %}">
            <span class="btn btn-block btn-danger" aria-hidden="true">Salir de la cuenta</span>&nbsp;
        </a>
        <form action="{% url 'managerApp:index'%}" method="post" class="" role="form">
            {% csrf_token %}
            <div>
                <button class="btn btn-block btn-info ripple-effect" type="submit" name="Submit" alt="sign in">Continuar</button>
            </div>
        </form>
    </div>
</div>


{% endblock %}

MercadoShark/managerApp/templates/managerApp/welcomeFirstTime.html
{% extends 'managerApp/base.html' %}
{% block body %}
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'managerApp/style_login.css' %}"/>

<div class="container">
    <div id="login" class="signin-card">
        <div class="logo-image">
            {% load staticfiles %}
            <img src="{%  static 'favicon.png' %}" alt="Logo" title="Logo" width="138" \>
        </div>
        <h3 style="text-align:center;" class="display1">Bienvenido a  <strong style='padding:0; height:33px;  font-family: "Satisfy", cursive;' >MercadoShark</strong>?</h3>
        <div class="subhead">
            <p style="text-align:justify;"><strong> MercadoShark </strong> es una aplicacion que te permite manejar mejor tus publicaciones de MercadoLibre.
             <br><br> Para comenzar debes iniciar sesion en Mercado Libre</p>
        </div>

        <form action="{% url 'managerApp:login_user' %}" method="post" class="" role="form">
            {% csrf_token %}
            <div>
                <button class="btn btn-block btn-info ripple-effect" type="submit" name="Submit" alt="sign in">Logearse en Mercado Libre</button>
            </div>
        </form>
    </div>
</div>


{% endblock %}